
services:
- type: web
  name: nlp-streamlit
  env: python
  buildCommand: pip install -r requirements.txt && python -m spacy download pt_core_news_sm
  startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
